
navbar:
  blog_title: 无名之辈

index:
  slogan:
    enable: true
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

post:
  comments:
    enable: true
    type: giscus


giscus:
  enable: true
  repo: WMD001/wmd001.github.io
  repo-id: R_kgDOJL9sYA
  category: Announcements
  category-id: DIC_kwDOJL9sYM4CXXTa
  # Available values: pathname | url | title | og:title
  mapping: title
  # Available values: 0 | 1 
  reactions-enabled: 1
   # Available values: 0 | 1 
  emit-metadata: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: light
  # Available values: en | zh-CN
  lang: zh-CN
