
navbar:
  blog_title: 无名之辈

favicon: /img/logo.png
apple_touch_icon: /img/logo.png

index:
  banner_img: /img/banner.png
  slogan:
    enable: true
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

custom_css: /css/custom.css

font:
  font_family: JetBrainsMono-LightItalic, Mono

post:
  banner_img: /img/banner.png
  comments:
    enable: true
    type: giscus


giscus:
  enable: true
  repo: WMD001/wmd001.github.io
  repo-id: R_kgDOJL9sYA
  category: Announcements
  category-id: DIC_kwDOJL9sYM4CXXTa
  # Available values: pathname | url | title | og:title
  mapping: title
  # Available values: 0 | 1 
  reactions-enabled: 1
   # Available values: 0 | 1 
  emit-metadata: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: light
  # Available values: en | zh-CN
  lang: zh-CN

about:
  name: "nobody"
  intro: "I'm nobody"
  avatar: /img/logo.png
  banner_img: /img/banner.png
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/wmd001', tip: 'GitHub' }
    - { class: 'iconfont icon-mail', link: 'mailto:habitdev@163.com', tip: 'Email' }