
navbar:
  blog_title: 无名之辈
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: "windows", link: "/windows", icon: "iconfont icon-th-large" }

favicon: /img/logo.png
apple_touch_icon: /img/logo.png

index:
  banner_img: /img/index.jpg
  slogan:
    enable: true
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

custom_css: /css/custom.css
custom_js: /js/custom.js

font:
  font_family: JetBrainsMono-LightItalic, Mono

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: /img/archive.png


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  banner_img: /img/category.jpg

#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  banner_img: /img/tag.jpg
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/post.jpg
  comments:
    enable: true
    type: giscus


giscus:
  enable: true
  repo: WMD001/wmd001.github.io
  repo-id: R_kgDOJL9sYA
  category: Announcements
  category-id: DIC_kwDOJL9sYM4CXXTa
  # Available values: pathname | url | title | og:title
  mapping: title
  # Available values: 0 | 1
  reactions-enabled: 1
   # Available values: 0 | 1
  emit-metadata: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: light
  # Available values: en | zh-CN
  lang: zh-CN

about:
  name: "nobody"
  intro: "I'm nobody"
  avatar: /img/logo.png
  banner_img: /img/about.jpg
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/wmd001', tip: 'GitHub' }
    - { class: 'iconfont icon-mail', link: 'mailto:habitdev@163.com', tip: 'Email' }
